# fly.toml app configuration file generated for esturide-api on 2024-11-17T17:27:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'esturide-api'
primary_region = 'gdl'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

# [[mounts]]
#   source = "db_data"
#   destination = "/data"
#   source = "logs"
#   destination = "/logs"
#   source = "import"
#   destination = "/var/lib/neo4j/import"
#   source = "plugins"
#   destination = "/plugins"

# [experimental]
#   allowed_public_ports = [8000, 7474, 7687]
#   auto_rollback = true
