name: Fly Deploy
on:
  push:
    branches:
      - deploy    # change to main if needed
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
  env:
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    DB_NAME: ${{ secrets.DB_NAME }}
    DB_USERNAME: ${{ secrets.DB_USERNAME }}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    DB_PORT: ${{ secrets.DB_PORT }}
    DB_URL: ${{ secrets.DB_URL }}
    SECRET_KEY: ${{ secrets.SECRET_KEY }}
    ALGORITHM: ${{ secrets.ALGORITHM }}
    ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
    API_HOST: ${{ vars.API_HOST }}
    API_PORT: ${{ vars.API_PORT }}